// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiC6yoSk7ehsopeR-mjabFsNH0SD2VlzY',
    appId: '1:37143214509:web:56e86167c8fb8137340924',
    messagingSenderId: '37143214509',
    projectId: 'smartphone-299f9',
    authDomain: 'smartphone-299f9.firebaseapp.com',
    storageBucket: 'smartphone-299f9.firebasestorage.app',
    measurementId: 'G-XXL9CH6D8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhxvQaHkPTu2gu0o8NP677eI2jV9NagHo',
    appId: '1:37143214509:android:0e68c983294eaf28340924',
    messagingSenderId: '37143214509',
    projectId: 'smartphone-299f9',
    storageBucket: 'smartphone-299f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9W4KhYKuY09k2gXWdHGjBpf2X_SsGdfs',
    appId: '1:37143214509:ios:18b5da3d3cef80e7340924',
    messagingSenderId: '37143214509',
    projectId: 'smartphone-299f9',
    storageBucket: 'smartphone-299f9.firebasestorage.app',
    iosBundleId: 'com.example.smartphoneApp',
  );
}
